// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterLevelAPI.Context;

#nullable disable

namespace WaterLevelAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713000000_CriarTabelaDeviceCommands")]
    partial class CriarTabelaDeviceCommands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("WaterLevelAPI.Model.DeviceCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PumpOn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceCommands");
                });

            modelBuilder.Entity("WaterLevelAPI.Model.WatterLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentLevel")
                        .HasColumnType("REAL");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxLevel")
                        .HasColumnType("REAL");

                    b.Property<double>("MinLevel")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimesTamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WaterLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
